[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "mechabellum-replay-parser"
version = "1.0.4"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "prettytable>=3.14.0",
]

[project.scripts]
mechabellum-replay-parser = "mechabellum_replay_parser.cli:main"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.sdist]
include = ["src/**", "tests/**"]


[bumpver]
current_version = "1.0.4"
version_pattern = "MAJOR.MINOR.PATCH"

[bumpver.file_patterns]
"pyproject.toml" = [
    'version = "{version}"',
]


[dependency-groups]
dev = [
    "bumpver>=2024.1130",
    "pytest>=8.3.4",
    "ruff>=0.9.7",
]
